#!/bin/bash
# chmod +x run.sh 로 실행 권한 부여 후 사용
# Brand Extraction - Full Pipeline
# 웹사이트에서 브랜드 자산 추출 + 분류 자동 실행

set -e

# 색상 정의
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# 사용법
usage() {
    echo "사용법: $0 --url <URL> --name <브랜드명> [--depth <깊이>]"
    echo ""
    echo "옵션:"
    echo "  --url     크롤링할 웹사이트 URL (필수)"
    echo "  --name    브랜드명/프로젝트명 (필수)"
    echo "  --depth   크롤링 깊이 (기본: 2)"
    echo ""
    echo "예시:"
    echo "  $0 --url https://example.com --name example-brand"
    exit 1
}

# 인자 파싱
URL=""
NAME=""
DEPTH=2

while [[ $# -gt 0 ]]; do
    case $1 in
        --url)
            URL="$2"
            shift 2
            ;;
        --name)
            NAME="$2"
            shift 2
            ;;
        --depth)
            DEPTH="$2"
            shift 2
            ;;
        *)
            usage
            ;;
    esac
done

# 필수 인자 확인
if [ -z "$URL" ] || [ -z "$NAME" ]; then
    usage
fi

# 경로 설정
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUTPUT_DIR="$SCRIPT_DIR/../output/$NAME"

echo -e "${GREEN}"
echo "============================================================"
echo "🚀 Brand Extraction Pipeline"
echo "============================================================"
echo -e "${NC}"
echo "URL:    $URL"
echo "Brand:  $NAME"
echo "Depth:  $DEPTH"
echo "Output: $OUTPUT_DIR"
echo ""

# 의존성 확인
echo -e "${YELLOW}📦 의존성 확인...${NC}"
pip install -q -r "$SCRIPT_DIR/requirements.txt"

# Step 1: 크롤링
echo -e "\n${YELLOW}[Step 1/3] 웹사이트 크롤링...${NC}"
python3 "$SCRIPT_DIR/crawler.py" \
    --url "$URL" \
    --output "$OUTPUT_DIR" \
    --depth "$DEPTH"

# Step 2: 이미지 분류
echo -e "\n${YELLOW}[Step 2/3] 이미지 분류...${NC}"
python3 "$SCRIPT_DIR/classifier.py" \
    --input "$OUTPUT_DIR/raw/images" \
    --output "$OUTPUT_DIR/classified" \
    --metadata "$OUTPUT_DIR/data/images.json"

# Step 3: 리포트 생성
echo -e "\n${YELLOW}[Step 3/3] 리포트 생성...${NC}"

REPORT_PATH="$OUTPUT_DIR/brand-report.md"
PAGES_COUNT=$(cat "$OUTPUT_DIR/data/pages.json" | python3 -c "import sys, json; print(len(json.load(sys.stdin)))" 2>/dev/null || echo "0")
IMAGES_COUNT=$(cat "$OUTPUT_DIR/data/images.json" | python3 -c "import sys, json; print(len(json.load(sys.stdin)))" 2>/dev/null || echo "0")
COLORS_COUNT=$(cat "$OUTPUT_DIR/data/colors.json" | python3 -c "import sys, json; print(len(json.load(sys.stdin)))" 2>/dev/null || echo "0")
FONTS_COUNT=$(cat "$OUTPUT_DIR/data/fonts.json" | python3 -c "import sys, json; print(len(json.load(sys.stdin)))" 2>/dev/null || echo "0")

cat > "$REPORT_PATH" << EOF
# Brand Extraction Report: $NAME

**소스**: $URL  
**추출일**: $(date '+%Y-%m-%d %H:%M')

## 요약

| 항목 | 수량 |
|------|------|
| 크롤링 페이지 | $PAGES_COUNT |
| 추출 이미지 | $IMAGES_COUNT |
| 색상 | $COLORS_COUNT |
| 폰트 | $FONTS_COUNT |

## 폴더 구조

\`\`\`
$NAME/
├── raw/images/          # 원본 이미지
├── classified/          # 분류된 이미지
│   ├── hero/
│   ├── product/
│   ├── icon/
│   ├── person/
│   ├── background/
│   ├── social/
│   └── misc/
├── data/
│   ├── pages.json
│   ├── images.json
│   ├── colors.json
│   └── fonts.json
└── brand-report.md
\`\`\`

## 다음 단계

1. \`classified/\` 폴더에서 이미지 확인 및 수동 재분류
2. \`data/colors.json\`에서 브랜드 컬러 확인
3. \`data/fonts.json\`에서 사용 폰트 확인
4. 필요한 자산을 프로젝트 폴더로 이동

---
*Generated by Brand Extraction Skill*
EOF

echo -e "\n${GREEN}"
echo "============================================================"
echo "✅ 완료!"
echo "============================================================"
echo -e "${NC}"
echo "📁 결과: $OUTPUT_DIR"
echo "📄 리포트: $REPORT_PATH"
echo ""
echo "다음 단계:"
echo "  1. $OUTPUT_DIR/classified/ 에서 분류된 이미지 확인"
echo "  2. 필요 시 수동으로 이미지 재분류"
echo "  3. 프로젝트 세팅으로 이동 (01_project-setup)"
